name: Publish Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits

      - name: Create changelog
        id: changelog
        uses: DevScyu/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          preset: conventionalcommits
          release-count: 0
          pre-commit: ./.github/.pre-commit.js
          config-file-path: ./.github/.config.js
          create-summary: true
          skip-git-pull: true

      - name: Upload version information
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.gradle.kts

  build:
    name: Build
    needs: [changelog] # Build needs the new version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3 # Download version information from changelog
        with:
          name: build

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: "gradle"

      - name: Build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs

  release-to-gh:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: [changelog, build]
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/libs

      - name: Rename artifact
        run: mv build/libs/HadesProtocol-*.jar build/HadesProtocol-${{ needs.changelog.outputs.tag }}.jar

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/HadesProtocol-${{ needs.changelog.outputs.tag }}.jar
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.clean_changelog }}

  publish:
    name: Publish to Github Packages
    runs-on: ubuntu-latest
    needs: [ build, changelog ]
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3 # Download version information from changelog
        with:
          name: build

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}